name: CI Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 21f3002924@ds.study.iitm.ac.in
        run: echo "Hello, world!"
